### ISSUE TITLE
Is that possible to run chroma locally? 

### ISSUE THREAD

**Issue by bjwswang** [amikos-tech/chroma-go#3]
Hi @tazarov .First of all nice work! People like me work on cloud native project really feels great to see a go client of chroma. However is it possible to run chroma locally ?

**Comment by tazarov** [comment]
@bjwswang, what do you mean locally? If that is a docker container on your local machine or private cloud VM, then yes, you can run it locally - see Chroma docs here - https://docs.trychroma.com/usage-guide#running-chroma-in-clientserver-mode

If you mean run locally without client/server mode, the answer is no. Chroma is written in Python, so only a Python client has the advantage of running it without an actual server; all other clients need a Chroma server to operate.

**Comment by bjwswang** [comment]
> @bjwswang, what do you mean locally? If that is a docker container on your local machine or private cloud VM, then yes, you can run it locally - see Chroma docs here - https://docs.trychroma.com/usage-guide#running-chroma-in-clientserver-mode
> 
> If you mean run locally without client/server mode, the answer is no. Chroma is written in Python, so only a Python client has the advantage of running it without an actual server; all other clients need a Chroma server to operate.

I see. Thanks! The latter one is what I was asking.   Cause I saw the examples in the chromadb repo.

**Comment by bjwswang** [comment]
> @bjwswang, what do you mean locally? If that is a docker container on your local machine or private cloud VM, then yes, you can run it locally - see Chroma docs here - https://docs.trychroma.com/usage-guide#running-chroma-in-clientserver-mode
> 
> If you mean run locally without client/server mode, the answer is no. Chroma is written in Python, so only a Python client has the advantage of running it without an actual server; all other clients need a Chroma server to operate.
When I tried the examples from the README doc, there are some tiny problmes. Do you mind I made a PR for that ?

**Comment by tazarov** [comment]
> When I tried the examples from the README doc, there are some tiny problmes. Do you mind I make a PR for that ?

Go ahead. I don't claim to be an expert in Golang :)
