### ISSUE TITLE
Move to Testcontainers instead of minikube

### ISSUE THREAD

**Issue by tazarov** [amikos-tech/chroma-go#51]
//chromaContainer, err := tc.RunContainer(context.Background(), testcontainers.WithImage("chromadb/chroma:0.4.22"))
		//if err != nil && strings.Contains(err.Error(), "Cannot connect to the Docker daemon") {
		//	t.Skip("Docker not available")
		//}
		//require.NoError(t, err)
		//t.Cleanup(func() {
		//	require.NoError(t, chromaContainer.Terminate(context.Background()))
		//})

**Comment by tazarov** [comment]
@bjwswang, makes it a bit easier to configure and work with as you can manage the external dependencies you need (e.g. Chroma server) programmatically, which makes CI a little easier (your mileage may vary)

**Comment by tazarov** [comment]
@mdelapenya, we are making the jump :)

**Comment by mdelapenya** [comment]
Great! Let's us know if we can be of any help
