### ISSUE TITLE
add log levels to make output message fine-grained

### ISSUE THREAD

**Issue by bjwswang** [amikos-tech/chroma-go#7]
Sometimes I don't want to print that much logs.

 For example,  https://github.com/amikos-tech/chroma-go/blob/main/main.go#L70   This should be a `debug` or `info` message.

**Comment by tazarov** [comment]
There are a whole lot of debug messages that need cleanup.

**Comment by tazarov** [comment]
Closing this as all logs, debug prints have been removed in #37
