### ISSUE TITLE
add context in EmbeddingFunction 

### ISSUE THREAD

**Issue by bjwswang** [amikos-tech/chroma-go#8]
Context is essential to avoid memory leak and pass signals to interrupt immediately.  That's why `golangci-lint` do the `contextcheck`. 
When I was trying to introduce chroma in langchaingo,  it failed at the lint tests as well.  See [here](https://github.com/tmc/langchaingo/actions/runs/6109091287/job/16579393153?pr=283) for more details.
So we should consider add context in embedding function

**Comment by tazarov** [comment]
thanks @bjwswang, let's go for context in embedding function
