### ISSUE TITLE
EmbeddingFunction - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jritsema** [amikos-tech/chroma-go#82]
Hello.  I'm trying to query a collection using the following code and am getting a `runtime error: invalid memory address or nil pointer dereference`

```go
collection, err := client.GetCollection(context.TODO(), "docs", nil)
collection.Query(context.TODO(), []string{text}, 10, nil, nil,
    []types.QueryEnum{types.IDocuments, types.IMetadatas})
```

```
github.com/amikos-tech/chroma-go.(*Collection).QueryWithOptions(0x1400007e4e0, {0x100e87838, 0x10119e580}, {0x14000263710, 0x5, 0xc19605ee206c7210?})
        /Users/john/.asdf/installs/golang/1.22.0/packages/pkg/mod/github.com/amikos-tech/chroma-go@v0.1.3/chroma.go:628 +0x268
github.com/amikos-tech/chroma-go.(*Collection).Query(0x10?, {0x100e87838?, 0x10119e580?}, {0x1400040b2d0?, 0x1400040b2c0?, 0x0?}, 0x0?, 0x1400040b2c0?, 0x100a888b0?, {0x140004aa980?, ...})
        /Users/john/.asdf/installs/golang/1.22.0/packages/pkg/mod/github.com/amikos-tech/chroma-go@v0.1.3/chroma.go:601 +0xf0
```

It looks like [EmbeddingFunction](https://github.com/amikos-tech/chroma-go/blob/main/chroma.go#L628) is required?  This seems to be optional in the Python client?

**Comment by tazarov** [comment]
@jritsema, thanks for reporting this. In the python client we have a default embedding function (core Chroma, not the chromadb-client package). While I try to maintain as much parity as possible this, the default EF is not one of those parities. However, the problem you encounter should not result in a nil pointer error. Let me fix that and also investigate how to add a default EF that uses all-miniLM model.

**Comment by tazarov** [comment]
@jritsema, a while ago I've added the ability to query without embedding function, in which case you'll have to provided the embedding vector.

```go
queryText, err := embeddingFunction.EmbedQuery(context.Background(), "Dogs are my favorite animals")
// error check
qr, err := col.QueryWithOptions(context.Background(), types.WithQueryEmbedding(queryText), types.WithNResults(5))
// error check
```

**Comment by jritsema** [comment]
Thanks @tazarov for the nil pointer fix!

> a while ago I've added the ability to query without embedding function, in which case you'll have to provided the embedding vector.

Does this mean I'll have to run a model to create embeddings myself?  

By default, Chroma uses the [Sentence Transformers](https://www.sbert.net/) all-MiniLM-L6-v2 model to create embeddings. Is it possible to include the all-miniLM model in this library?  Or will the code you referenced above do that? (I apologize if my question doesn't make sense, I'm somewhat new to this space)

**Comment by tazarov** [comment]
@jritsema, to run `all-MiniLM-L6-v2` there are several options:

- Embedded mode (within the go app) - llama.cpp (there are several bindings), onnx runtime (again several bindings for go)
- Remote (kind of local with docker) ollama (local), HF Text Embeddings Inference Server

Let me know if you need an example for the above.

I have considered adding embedded support however it requires some extra steps on behalf of the dev which are not always straightofward so I'm a bit skeptical about it, but always keeping an eye on things.

**Comment by jritsema** [comment]
Thanks @tazarov.  Are you saying I can run the `all-MiniLM-L6-v2` model in Ollama and then make this library call it?
