### ISSUE TITLE
Link to get more info is broke - https://go-client.chromadb.dev/auth/

### ISSUE THREAD

**Issue by anguianoa** [amikos-tech/chroma-go#90]
On the code page there is this.

We invite users to visit the docs site for the library for more in-depth information: [Chroma Go Docs](https://go-client.chromadb.dev/auth/)

this link gets a 404

Also, is there an example on how to make this work with ollama?

**Comment by tazarov** [comment]
@anguianoa, GH breaks the page ref to the domain for some reason. I'll investigate further.

Regarding Ollama (assuming you are talking about using embedding models) - https://go-client.chromadb.dev/embeddings/#ollama

**Comment by tazarov** [comment]
Closing. Let me know if the ollama integration I linked above is what you needed?
